import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from "../components/organisms/Navbar"
import Footer from "../components/organisms/Footer";
import TipCard from '../components/molecules/TipCard'
import MatchCard from '../components/molecules/featuredMatches'
import { Heading, Img } from '@chakra-ui/react'
import Para from '../components/molecules/para/Para'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Free Sports Bettings Tips</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={styles.main}>
          

        <TipCard
          date="Today . 21:00"
          title="Bet of the day tip"
          tipped_at="7/4"
        />
        <TipCard
          date="Today . 17:30"
          title="Boxing Day Experts' Accumulator tip"
          tipped_at="394/1"
        />
        <TipCard
          date="Today . 15:00"
          title="Both teams to score & win trebale trip"
          tipped_at="71/1"
        />
        <TipCard
          date="Today . 20:00"
          title="Boxing day TV & Accumulator tip"
          tipped_at="153/1"
        />
        <TipCard
          date="Today . 14:00"
          title="Both teams to score & win Accumulator tip"
          tipped_at="7/1"
        />
        <TipCard
          date="Today . 10:00"
          title="Sky super six & Accumulator tip"
          tipped_at="81/9"
        />
        <TipCard
          date="Today . 21:00"
          title="Christmas ACCR tip"
          tipped_at="139/1"
        />
        <TipCard
          date="Tomorrow . 21:00"
          title="Correct Score double tip"
          tipped_at="47/1"
        />
        <TipCard
          date="Tomorrow . 21:00"
          title="Arsenal vs West ham bet buider tip"
          tipped_at="45/1"
        />
        <TipCard
          date="Today . 21:00"
          title="Turkish Super lig & Accumulator tip"
          tipped_at="12/1"
        />
        <TipCard
          date="Today . 21:00"
          title="Bet of the day tip"
          tipped_at="58/1"
        />
        <div className='bottom-cards'>
        <TipCard
          date="Tomorrow . 21:00"
          title="3pm Accumulator tip"
          tipped_at="7/4"
        />
        <TipCard
          date="Today . 21:00"
          title="Match goals Accumulator tip"
          tipped_at="6/1"
        />
        <TipCard
          date="Today . 21:00"
          title="Bet to Net Mega Accumulator tip"
          tipped_at="7/4"
        />
        <TipCard
          date="Bet of the day tip"
          title="Tomorrow . 21:00"
          tipped_at="7/4"
        />
        <TipCard
          date="Tomorrow . 21:00"
          title="Bet of the day tip"
          tipped_at="7/4"
        />
        <TipCard
          date="Tomorrow . 21:00"
          title="Bet of the day tip"
          tipped_at="7/4"
        />

        <MatchCard


          flag={"image to set"}
          teamName={"Watford"}
          date={"21:00"}  
          title={"image to be set"}
          secondTeam={"Portugal Vs Argentina"}
          
        />        
        </div>

      <div className='Para'>
      <Para
      // firstHeading={"Your Football Website"}
      />
      

      </div>

      </main>
      <Footer/>
    </>
  )
}
